### ISSUE TITLE
tianon/true Exited

### ISSUE THREAD

**Issue by jujes** [htdvisser/taiga-docker#20]
Hi for some reason data container is not loaded... someone know why?
**nothing to show in docker logs...**

![screen shot 2016-06-22 at 11 43 24](https://cloud.githubusercontent.com/assets/2881017/16262147/bdcb1618-386e-11e6-9194-4c7e96f7dca7.png)

**Comment by beevelop** [comment]
> Data-only containers are a pattern for managing your docker volumes with containers instead of manually with host-mounted volumes.

They are not supposed to be kept running. Due to Docker's recent development this concept can also be achieved by using **Docker Volumes**.

Refer to:
- https://docs.docker.com/engine/tutorials/dockervolumes/#data-volumes
- https://getcarina.com/docs/tutorials/data-volume-containers/
- http://container42.com/2013/12/16/persistent-volumes-with-docker-container-as-volume-pattern/
